[package]
name = "wallet-core"
version = "0.3.1"
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Vincent Hanquez <vincent@typed.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = { version = "1.0.13", default-features = false }
bip39 = { path = "../../bip39" }
wallet = { path = "../../wallet" }
chain-core = { path = "../../chain-deps/chain-core" }
chain-ser = { path = "../../chain-deps/chain-ser" }
chain-addr = { path = "../../chain-deps/chain-addr" }
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain" }