[package]
name = "wallet-uniffi"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = [ "cdylib" ]
name = "uniffi_jormungandr_wallet"

[dependencies]
uniffi = "0.16.0"
uniffi_macros = "0.16.0"
wallet-core = { path = "../wallet-core" }
wallet = {path = "../../wallet"}
symmetric-cipher = {path = "../../symmetric-cipher"}
chain-vote = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "catalyst-fund9" }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "catalyst-fund9" }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "catalyst-fund9" }
chain-crypto = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "catalyst-fund9" }
chain-time = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "catalyst-fund9" }
chain-ser = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "catalyst-fund9" }
thiserror = {version = "1.0", default-features = false}

[build-dependencies]
uniffi_build = "0.16.0"

[features]
builtin-bindgen = ["uniffi_build/builtin-bindgen"]
